# Generated by Django 5.0 on 2023-12-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CarDb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("maker", models.CharField(max_length=30, null=True)),
                ("genmodel", models.CharField(max_length=30, null=True)),
                ("genmodel_id", models.CharField(max_length=30, null=True)),
                ("adv_id", models.CharField(max_length=30, null=True)),
                ("adv_year", models.CharField(max_length=30, null=True)),
                ("adv_month", models.CharField(max_length=30, null=True)),
                ("colour", models.CharField(max_length=30, null=True)),
                ("reg_year", models.CharField(max_length=30, null=True)),
                ("bodytype", models.CharField(max_length=30, null=True)),
                ("mileage", models.CharField(max_length=30, null=True)),
                ("engine_size", models.CharField(max_length=30, null=True)),
                ("gearbox", models.CharField(max_length=30, null=True)),
                ("fuel_type", models.CharField(max_length=30, null=True)),
                ("price", models.CharField(max_length=30, null=True)),
                ("seat_num", models.CharField(max_length=30, null=True)),
                ("door_num", models.CharField(max_length=30, null=True)),
            ],
            options={
                "db_table": "ad_table",
            },
        ),
    ]
